import { useState } from "react";
import { Mail, MessageCircle, ShieldCheck, SlidersHorizontal } from "lucide-react";
import type { Operation, WorkspaceState } from "./domain";
import { Drawer } from "./DirectoryPages";
import { findRecord, recordInput, type WorkspaceRecord } from "./records";
import type { Repository } from "./repository";
import { activeTracks, casualRequest, clientTracks, emailMessageUrl, restrictionOptions, whatsappMessageUrl } from "./clientFlow";
import "./clientFlow.css";

export function ContactButtons({op,records,notify}:{op:Operation;records:WorkspaceRecord[];notify:(s:string)=>void}) {
  const [channel,setChannel]=useState<"WhatsApp"|"E-mail"|null>(null);
  return <><div className="client-contact-buttons"><button type="button" aria-label={`WhatsApp de ${op.company}`} title={op.phone||"Cadastrar telefone"} onClick={()=>setChannel("WhatsApp")}><MessageCircle size={15}/><span>WhatsApp</span></button><button type="button" aria-label={`E-mail de ${op.company}`} title={op.email||"Cadastrar e-mail"} onClick={()=>setChannel("E-mail")}><Mail size={15}/><span>E-mail</span></button></div>{channel&&<CommunicationDrawer key={channel} op={op} records={records} channel={channel} close={()=>setChannel(null)} notify={notify}/>}</>;
}
export function CommunicationDrawer({op,records,channel,close,notify}:{op:Operation;records:WorkspaceRecord[];channel:"WhatsApp"|"E-mail";close:()=>void;notify:(s:string)=>void}) {
  const [text,setText]=useState(()=>casualRequest(op,records)),[subject,setSubject]=useState(`Documentação · ${op.company} · LR Capital`),[error,setError]=useState("");
  const url=channel==="WhatsApp"?whatsappMessageUrl(op.phone,text):emailMessageUrl(op.email,subject,text);
  return <Drawer title={`${channel} · ${op.company}`} close={close}><div className="module-form"><p>A mensagem usa as pendências atuais. Revise antes de abrir a conversa. O envio é concluído por você no {channel}.</p><div className="contact-recipient"><strong>Destinatário</strong><span>{channel==="WhatsApp"?op.phone||"Telefone não cadastrado":op.email||"E-mail não cadastrado"}</span></div>{channel==="E-mail"&&<label>Assunto<input value={subject} maxLength={180} onChange={e=>setSubject(e.target.value)}/></label>}<label>Mensagem<textarea rows={15} value={text} maxLength={16000} onChange={e=>setText(e.target.value)}/></label><div className="module-actions"><button onClick={()=>{setText(casualRequest(op,records));setError("");}}>Atualizar pelas pendências</button><button onClick={async()=>{try{await navigator.clipboard.writeText(text);notify("Mensagem copiada.");}catch{setError("Não foi possível copiar. Selecione e copie o texto.");}}}>Copiar mensagem</button></div>{url&&text.trim()?<a className="contact-open" href={url} target={channel==="WhatsApp"?"_blank":undefined} rel="noreferrer">Abrir {channel} com mensagem ↗</a>:<p className="module-warning">Confira o {channel==="WhatsApp"?"telefone com DDD":"e-mail"} em Dados do cliente antes de abrir a conversa.</p>}{error&&<p role="alert">{error}</p>}<p className="module-footnote">Abrir a conversa não marca documentos como solicitados ou enviados. Mensagens longas podem exigir copiar o texto para o aplicativo.</p></div></Drawer>;
}
export function ClientClassification({op,state,repo,canEdit,notify}:{op:Operation;state:WorkspaceState;repo:Repository;canEdit:boolean;notify:(s:string)=>void}) {
  const [open,setOpen]=useState(false),profile=findRecord(state.records??[],"profile",op.id),restriction=profile?.data.restriction||"A verificar";
  return <><button type="button" className={`client-classification ${restriction==="Com restrições"?"has-restriction":""}`} aria-label={`Restrições e atuação de ${op.company}`} onClick={()=>setOpen(true)}><ShieldCheck size={13}/>{restriction}<SlidersHorizontal size={13}/></button>{open&&<ClassificationDrawer op={op} state={state} repo={repo} canEdit={canEdit} notify={notify} close={()=>setOpen(false)}/>}</>;
}
function ClassificationDrawer({op,state,repo,canEdit,notify,close}:{op:Operation;state:WorkspaceState;repo:Repository;canEdit:boolean;notify:(s:string)=>void;close:()=>void}) {
  const [profile]=useState(()=>findRecord(state.records??[],"profile",op.id)),[restriction,setRestriction]=useState(profile?.data.restriction||"A verificar"),[tracks,setTracks]=useState(()=>activeTracks(op,state.records??[])),[busy,setBusy]=useState(false),[error,setError]=useState("");
  return <Drawer title="Restrições e frentes de atuação" close={()=>{if(!busy)close();}}><form className="module-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{await repo.saveRecord(recordInput("profile",op.id,{address:"",city:"",state:"",segment:"",...profile?.data,restriction,activeTracks:tracks},profile?.id),profile?.version??null);notify("Restrições e frentes de atuação atualizadas.");close();}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar.");}finally{setBusy(false);}}}><p>{op.company}</p><fieldset disabled={!canEdit||busy}><h3>Situação informada</h3><div className="classification-choices" role="group" aria-label="Situação de restrição">{restrictionOptions.map(s=><button type="button" aria-pressed={restriction===s} key={s} onClick={()=>setRestriction(s)}>{s}</button>)}</div><p className="module-footnote">Classificação da equipe; não realiza consulta a birôs nem altera a decisão de crédito.</p><h3>Frentes em acompanhamento</h3><p>Marque todas as possibilidades em que estão trabalhando com este cliente.</p><div className="classification-choices">{clientTracks.map(s=><button type="button" key={s} aria-pressed={tracks.includes(s)} onClick={()=>setTracks(tracks.includes(s)?tracks.filter(t=>t!==s):[...tracks,s])}>{tracks.includes(s)?"✓ ":"+ "}{s}</button>)}</div><p className="module-footnote">As marcações organizam a carteira e a documentação mínima. As condições de cada instituição permanecem no seu vínculo.</p></fieldset>{error&&<p role="alert" className="module-error">{error}</p>}<button className="primary" disabled={!canEdit||busy}>{busy?"Salvando…":"Salvar classificação"}</button></form></Drawer>;
}
