import { useMemo, useState } from "react";
import { Mail, MessageCircle, ShieldCheck, SlidersHorizontal } from "lucide-react";
import type { Operation, WorkspaceState } from "./domain";
import { Drawer } from "./DirectoryPages";
import { findRecord, recordInput, type WorkspaceRecord } from "./records";
import type { Repository } from "./repository";
import { activeTracks, clientTracks, emailMessageUrl, restrictionOptions, whatsappMessageUrl } from "./clientFlow";
import "./clientFlow.css";
import {communicationChecklist, checklistFingerprint, receivedDocument, reviewedRequest} from "./documentReview";
import {requestableDocuments} from "./clientFlow";
import {checklistId,expiredDocument} from "./workflow";

type ContactProps={op:Operation;records:WorkspaceRecord[];repo:Repository;canEdit:boolean;notify:(s:string)=>void};
export function ContactButtons(props:ContactProps) {
 const [channel,setChannel]=useState<"WhatsApp"|"E-mail"|null>(null);
 return <><div className="client-contact-buttons"><button type="button" aria-label={"WhatsApp de "+props.op.company} title={props.op.phone||"Cadastrar telefone"} onClick={()=>setChannel("WhatsApp")}><MessageCircle size={15}/><span>WhatsApp</span></button><button type="button" aria-label={"E-mail de "+props.op.company} title={props.op.email||"Cadastrar e-mail"} onClick={()=>setChannel("E-mail")}><Mail size={15}/><span>E-mail</span></button></div>{channel&&<CommunicationDrawer {...props} key={channel} channel={channel} close={()=>setChannel(null)}/>}</>;
}
export function CommunicationDrawer({op,records,repo,canEdit,channel,close,notify}:ContactProps&{channel:"WhatsApp"|"E-mail";close:()=>void}) {
 const [text,setText]=useState(""),[subject,setSubject]=useState("Documentação · "+op.company+" · LR Capital"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[marked,setMarked]=useState<string[]>([]),[excluded,setExcluded]=useState<string[]>([]),[location,setLocation]=useState(""),[reviewed,setReviewed]=useState(false),[base,setBase]=useState("");
 const items=useMemo(()=>communicationChecklist(op,records),[op,records]),requestable=requestableDocuments(op,records),fingerprint=checklistFingerprint(op,records);
 const ready=reviewed&&base===fingerprint&&!marked.length;
 const url=channel==="WhatsApp"?whatsappMessageUrl(op.phone,text):emailMessageUrl(op.email,subject,text);
 async function prepare(){setBusy(true);setError("");let saved=0;try{let effective=[...records];for(const id of marked){const row=items.find(r=>r.id===id);if(!row)throw Error("A lista mudou. Revise os documentos.");const recordId=row.version?row.id:await checklistId(op.id,row.data.templateKey);const data=receivedDocument(row,location,repo.session?.name||op.owner);await repo.saveRecord(recordInput("document",op.id,data,recordId),row.version||null);effective=effective.filter(r=>r.id!==recordId);effective.push({...row,id:recordId,data,version:row.version+1});saved++;setMarked(old=>old.filter(x=>x!==id));}
 const selected=new Set(requestableDocuments(op,effective).filter(r=>!excluded.includes(r.id)).map(r=>r.id));setText(reviewedRequest(op,effective,selected));setBase(checklistFingerprint(op,effective));setReviewed(true);if(saved)notify(saved+" documentos marcados como recebidos, aguardando conferência.");
 }catch(e){setReviewed(false);setError((saved?saved+" recebimentos salvos. ":"")+(e instanceof Error?e.message:"Não foi possível salvar. Revise antes de continuar."));}finally{setBusy(false);}}
 return <Drawer title={channel+" · "+op.company} close={()=>!busy&&close()}><div className="module-form"><p>Confira o que já chegou e escolha somente o que precisa solicitar. As marcações de recebimento ficam salvas para toda a equipe.</p><div className="contact-recipient"><strong>Destinatário</strong><span>{channel==="WhatsApp"?op.phone||"Telefone não cadastrado":op.email||"E-mail não cadastrado"}</span></div>
 <h3>Revisar documentos antes da mensagem</h3><div className="receipt-checklist">{items.map(row=>{const pending=requestable.some(r=>r.id===row.id),received=["Recebido","Em conferência","Conferido"].includes(row.data.status)&&!expiredDocument(row);return <div className="receipt-row" key={row.id}><div><strong>{row.data.title}</strong><small>{row.data.period||"Período a conferir"} · {expiredDocument(row)?"Vencido — atualize a versão":row.data.status}</small></div><label><input type="checkbox" aria-label={"Já recebido: "+row.data.title} checked={received||marked.includes(row.id)} disabled={busy||!canEdit||received||expiredDocument(row)||row.data.status==="Dispensado"} onChange={e=>{setMarked(e.target.checked?[...marked,row.id]:marked.filter(id=>id!==row.id));setReviewed(false);}}/> Já recebido</label>{pending&&!marked.includes(row.id)&&<label><input type="checkbox" aria-label={"Solicitar: "+row.data.title} checked={!excluded.includes(row.id)} disabled={busy} onChange={e=>{setExcluded(e.target.checked?excluded.filter(id=>id!==row.id):[...excluded,row.id]);setReviewed(false);}}/> Solicitar</label>}</div>;})}</div>
 {marked.length>0&&<label>Onde estão os documentos que você marcou?<input value={location} onChange={e=>setLocation(e.target.value)} maxLength={500} placeholder="Ex.: pasta do Drive, e-mail recebido hoje ou anexo neste e-mail"/><small>Recebimento informado pela equipe; o conteúdo ainda será conferido.</small></label>}
 <button className="primary" disabled={busy} onClick={()=>void prepare()}>{busy?"Salvando revisão…":marked.length?"Salvar recebimentos e preparar mensagem":"Confirmar checklist e preparar mensagem"}</button>
 {reviewed&&!ready&&<p role="alert">O cadastro mudou. Confirme o checklist novamente para atualizar a mensagem.</p>}
 {channel==="E-mail"&&<label>Assunto<input value={subject} maxLength={180} onChange={e=>setSubject(e.target.value)}/></label>}<label>Mensagem para revisar<textarea rows={12} value={text} maxLength={16000} placeholder="Confirme o checklist acima para preparar a mensagem." onChange={e=>setText(e.target.value)}/></label>
 <div className="module-actions"><button disabled={!ready||!text.trim()||busy} onClick={async()=>{try{await navigator.clipboard.writeText(text);notify("Mensagem copiada.");}catch{setError("Selecione e copie o texto manualmente.");}}}>Copiar mensagem</button>{ready&&url&&text.trim()&&!busy?<a className="contact-open" href={url} target={channel==="WhatsApp"?"_blank":undefined} rel="noreferrer">Abrir {channel} com mensagem ↗</a>:<button disabled>Abrir {channel} com mensagem</button>}</div>{!url&&<p className="module-warning">Confira o {channel==="WhatsApp"?"telefone com DDD":"e-mail"} em Dados do cliente.</p>}{error&&<p role="alert" className="module-error">{error}</p>}<p className="module-footnote">O envio e os anexos são feitos por você no {channel}. Abrir a conversa não registra um envio concluído. Itens recebidos não são considerados conferidos.</p></div></Drawer>;
}
export function ClientClassification({op,state,repo,canEdit,notify}:{op:Operation;state:WorkspaceState;repo:Repository;canEdit:boolean;notify:(s:string)=>void}) {
  const [open,setOpen]=useState(false),profile=findRecord(state.records??[],"profile",op.id),restriction=profile?.data.restriction||"A verificar";
  return <><button type="button" className={`client-classification ${restriction==="Com restrições"?"has-restriction":""}`} aria-label={`Restrições e atuação de ${op.company}`} onClick={()=>setOpen(true)}><ShieldCheck size={13}/>{restriction}<SlidersHorizontal size={13}/></button>{open&&<ClassificationDrawer op={op} state={state} repo={repo} canEdit={canEdit} notify={notify} close={()=>setOpen(false)}/>}</>;
}
function ClassificationDrawer({op,state,repo,canEdit,notify,close}:{op:Operation;state:WorkspaceState;repo:Repository;canEdit:boolean;notify:(s:string)=>void;close:()=>void}) {
  const [profile]=useState(()=>findRecord(state.records??[],"profile",op.id)),[restriction,setRestriction]=useState(profile?.data.restriction||"A verificar"),[tracks,setTracks]=useState(()=>activeTracks(op,state.records??[])),[busy,setBusy]=useState(false),[error,setError]=useState("");
  return <Drawer title="Restrições e frentes de atuação" close={()=>{if(!busy)close();}}><form className="module-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{await repo.saveRecord(recordInput("profile",op.id,{address:"",city:"",state:"",segment:"",...profile?.data,restriction,activeTracks:tracks},profile?.id),profile?.version??null);notify("Restrições e frentes de atuação atualizadas.");close();}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar.");}finally{setBusy(false);}}}><p>{op.company}</p><fieldset disabled={!canEdit||busy}><h3>Situação informada</h3><div className="classification-choices" role="group" aria-label="Situação de restrição">{restrictionOptions.map(s=><button type="button" aria-pressed={restriction===s} key={s} onClick={()=>setRestriction(s)}>{s}</button>)}</div><p className="module-footnote">Classificação da equipe; não realiza consulta a birôs nem altera a decisão de crédito.</p><h3>Frentes em acompanhamento</h3><p>Marque todas as possibilidades em que estão trabalhando com este cliente.</p><div className="classification-choices">{clientTracks.map(s=><button type="button" key={s} aria-pressed={tracks.includes(s)} onClick={()=>setTracks(tracks.includes(s)?tracks.filter(t=>t!==s):[...tracks,s])}>{tracks.includes(s)?"✓ ":"+ "}{s}</button>)}</div><p className="module-footnote">As marcações organizam a carteira e a documentação mínima. As condições de cada instituição permanecem no seu vínculo.</p></fieldset>{error&&<p role="alert" className="module-error">{error}</p>}<button className="primary" disabled={!canEdit||busy}>{busy?"Salvando…":"Salvar classificação"}</button></form></Drawer>;
}
