import type { Operation } from "./domain";
// Fictional preview data. Never imported by the production Firebase repository.
export function sampleOperations(): Operation[] {
  const stamp = new Date().toISOString();
  const day = (offset: number) => {
    const d = new Date();
    d.setDate(d.getDate() + offset);
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
  };
  const base = {
    cnpj: "",
    contact: "",
    email: "",
    phone: "",
    approvedCents: null,
    revenueCents: null,
    version: 1,
    createdAt: stamp,
    updatedAt: stamp,
    notes: "Registro fictício para experimentar a nova interface.",
  };
  return [
    {
      ...base,
      id: "demo-atlas",
      company: "Atlas Indústria",
      product: "Capital de giro",
      stage: "Mesa de crédito",
      owner: "Ricardo",
      requestedCents: 200000000,
      nextAction: "Acompanhar retorno da mesa e confirmar prazo.",
      dueDate: day(0),
      institution: "Banco de exemplo A",
    },
    {
      ...base,
      id: "demo-horizonte",
      company: "Horizonte Alimentos",
      product: "Antecipação de recebíveis",
      stage: "Análise",
      owner: "Loreni",
      requestedCents: 85000000,
      nextAction: "Conferir carteira de recebíveis recebida.",
      dueDate: day(-2),
      institution: "Fundo de exemplo B",
    },
    {
      ...base,
      id: "demo-vertice",
      company: "Vértice Logística",
      product: "Financiamento",
      stage: "Documentação",
      owner: "Giovani",
      requestedCents: 150000000,
      nextAction: "Solicitar balanço e relação de endividamento.",
      dueDate: day(1),
      institution: "",
    },
    {
      ...base,
      id: "demo-aurora",
      company: "Aurora Embalagens",
      product: "Capital de giro",
      stage: "Aprovado",
      owner: "Ricardo",
      requestedCents: 300000000,
      approvedCents: 250000000,
      nextAction: "Conferir condições da proposta aprovada.",
      dueDate: day(2),
      institution: "Banco de exemplo C",
    },
    {
      ...base,
      id: "demo-mirante",
      company: "Mirante Comércio",
      product: "Home equity",
      stage: "Documentação",
      owner: "Ketlin",
      requestedCents: 95000000,
      nextAction: "Conferir documentação da garantia.",
      dueDate: day(0),
      institution: "Instituição de exemplo D",
    },
    {
      ...base,
      id: "demo-nova",
      company: "Nova Terra Serviços",
      product: "Capital de giro",
      stage: "Novo",
      owner: "Loreni",
      requestedCents: 50000000,
      nextAction: "Agendar conversa de diagnóstico.",
      dueDate: day(3),
      institution: "",
    },
    {
      ...base,
      id: "demo-sul",
      company: "Sul Equipamentos",
      product: "Financiamento",
      stage: "Liberado",
      owner: "Giovani",
      requestedCents: 120000000,
      approvedCents: 120000000,
      nextAction: "Registrar fechamento da operação.",
      dueDate: "",
      institution: "Banco de exemplo A",
    },
    {
      ...base,
      id: "demo-porto",
      company: "Porto Soluções",
      product: "Capital de giro",
      stage: "Retomada",
      owner: "Ketlin",
      requestedCents: null,
      nextAction: "Retomar contato no próximo mês.",
      dueDate: day(20),
      institution: "",
    },
  ] as Operation[];
}
