import {useEffect,useState} from "react";
import {Copy,UserPlus,ShieldCheck} from "lucide-react";
import type {Repository} from "./repository";
import {invitationInput,type AccessRole,type TeamState} from "./team";
export function TeamAccess({repo,notify}:{repo:Repository;notify:(s:string)=>void}) {
 const [state,setState]=useState<TeamState>({members:[],invitations:[]}),[name,setName]=useState(""),[email,setEmail]=useState(""),[role,setRole]=useState<AccessRole>("editor"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>repo.subscribeTeam?.(setState,setError),[repo]);
 const accessLink=repo.mode==="firebase"?location.origin:"https://lr-capital-crm-v2-2026.web.app";
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError("");try{await fn();}catch(e){setError(e instanceof Error?e.message:"Não foi possível atualizar o acesso.");}finally{setBusy(false);}};
 return <section className="surface team-access"><div className="team-heading"><span className="setting-symbol"><ShieldCheck size={24}/></span><div><h2>Usuários e acesso Google</h2><p>Cadastre o e-mail usado na conta Google e compartilhe o link com seu sócio.</p></div></div>{!repo.saveInvitation&&<p className="module-warning">O cadastro de acesso está disponível no sistema publicado. A prévia não cria usuários reais.</p>}
 <form className="module-form" onSubmit={e=>{e.preventDefault();void act(async()=>{const input=invitationInput(email,name,role);if(state.members.some(m=>m.email?.toLowerCase()===input.email))throw Error("Este usuário já está cadastrado. Ajuste o acesso na lista abaixo.");const existing=state.invitations.find(i=>i.email===input.email);if(existing?.claimedUid)throw Error("Este convite já foi utilizado. Ajuste o acesso na lista abaixo.");if(!repo.saveInvitation)throw Error("Abra o sistema publicado para cadastrar o usuário.");await repo.saveInvitation({...input,active:true},existing?.version??null);setEmail("");setName("");notify("Acesso cadastrado. Copie o link e compartilhe com seu sócio.");});}}><fieldset disabled={busy||!repo.saveInvitation}><div className="module-grid"><label>Nome do usuário<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>E-mail da conta Google<input required type="email" maxLength={180} value={email} onChange={e=>setEmail(e.target.value)} placeholder="socio@gmail.com"/></label><label>Permissão<select value={role} onChange={e=>setRole(e.target.value as AccessRole)}><option value="editor">Editar a carteira</option><option value="reader">Somente consultar</option></select></label></div><button className="primary"><UserPlus size={16}/> Cadastrar usuário</button></fieldset></form>
 <div className="team-link"><span>{accessLink}</span><button onClick={()=>void act(async()=>{await navigator.clipboard.writeText(accessLink);notify("Link de acesso copiado.");})}><Copy size={14}/> Copiar link de acesso</button></div><p className="module-footnote">No link, o sócio escolhe “Entrar com Google” e usa exatamente o e-mail cadastrado. Nenhuma senha é compartilhada e nenhum e-mail é enviado automaticamente.</p>
 {error&&<p role="alert" className="module-error">{error}</p>}
 <h3>Equipe</h3><div className="team-list">{state.members.map(m=><div className="team-person" key={m.uid}><div><strong>{m.name}</strong><small>{m.email|| (m.uid===repo.session?.uid?repo.session.email:"")}</small></div>{m.role==="admin"?<span>Administrador · ativo</span>:<><select aria-label={`Permissão de ${m.name}`} disabled={busy} value={m.role} onChange={e=>void act(()=>repo.changeMemberAccess!(m,m.active,e.target.value as AccessRole))}><option value="editor">Editar</option><option value="reader">Consultar</option></select><button disabled={busy} onClick={()=>void act(()=>repo.changeMemberAccess!(m,!m.active,m.role as AccessRole))}>{m.active?"Desativar acesso":"Reativar acesso"}</button></>}</div>)}</div>
 <h3>Convites aguardando primeiro acesso</h3>{state.invitations.filter(i=>!i.claimedUid).map(i=><div className="team-person" key={i.email}><div><strong>{i.name}</strong><small>{i.email} · {i.active?"Aguardando acesso":"Revogado"} · {i.role==="reader"?"Consulta":"Edição"}</small></div><button disabled={busy} onClick={()=>void act(()=>repo.saveInvitation!({...i,active:!i.active},i.version))}>{i.active?"Revogar":"Reativar"}</button></div>)}
 </section>;
}
