import { useEffect, useMemo, useState } from "react";
import { ArrowRight, ClipboardCheck, Copy, FileText, FolderOpen, Plus, Send, Upload, Clock3 } from "lucide-react";
import { displayDate, products, today, type Operation, type WorkspaceState } from "./domain";
import { Drawer } from "./DirectoryPages";
import { RecordEditor } from "./ClientPortfolio";
import { recordInput, type RecordEvent, type WorkspaceRecord } from "./records";
import type { Repository } from "./repository";
import { categories, checklistId, clientUpdateDraft, documentChecklist, documentStatuses, expiredDocument, followUps, newDocument, newTask, openDispatch, openTask, pendingDocument, readyDocument, requestDraft, signatureChecks, waitingParties, type DocumentFile } from "./workflow";
import { normalizeSearch } from "./portfolio";
import "./workflow.css";

type Props = { state: WorkspaceState; repo: Repository; canEdit: boolean; selectedId: string; select: (id: string) => void; notify: (message: string) => void; initialTab?: WorkflowTab; onEditClient: (op: Operation) => void };
export type WorkflowTab = "documents" | "tasks" | "dispatches" | "client";
const errorText = (e: unknown) => e instanceof Error ? e.message : "Não foi possível concluir.";
const dateClass = (date: string) => date && date < today() ? "workflow-overdue" : "";
const empty = (text: string) => <div className="workflow-empty"><FolderOpen size={25} /><p>{text}</p></div>;

export function WorkflowPage({ state, repo, canEdit, selectedId, select, notify, onEditClient, initialTab = "documents" }: Props) {
  const [search, setSearch] = useState("");
  const [tab, setTab] = useState<WorkflowTab>(initialTab);
  const [documentFilter, setDocumentFilter] = useState("Todos");
  const [archived, setArchived] = useState(false);
  const [editing, setEditing] = useState<{ kind: "document" | "task" | "dispatch" | "files" | "placement"; record: WorkspaceRecord | null; placementId?: string } | null>(null);
  const [template, setTemplate] = useState(false);
  const [draft, setDraft] = useState<{ title: string; text: string } | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { setTab(initialTab); setEditing(null); setDocumentFilter("Todos"); setArchived(false); setDraft(null); setTemplate(false); }, [selectedId, initialTab]);
  const op = state.operations.find((o) => o.id === selectedId);
  const records = (state.records ?? []).filter((r) => r.operationId === selectedId);
  const docs = records.filter((r) => r.kind === "document" && !!r.data.archived === archived);
  const activeDocs = records.filter((r) => r.kind === "document" && !r.data.archived);
  const tasks = records.filter((r) => r.kind === "task");
  const dispatches = records.filter((r) => r.kind === "dispatch").sort((a, b) => b.data.sentOn.localeCompare(a.data.sentOn));
  const placements = records.filter((r) => r.kind === "placement");
  const pending = activeDocs.filter((r) => pendingDocument(r));
  const awaitingClient = pending.filter((r) => !["Recebido", "Em conferência"].includes(r.data.status) || expiredDocument(r));
  const toReview = activeDocs.filter((r) => ["Recebido", "Em conferência"].includes(r.data.status) && !expiredDocument(r));
  const ready = activeDocs.filter((r) => readyDocument(r));
  const shownDocs = docs.filter((r) => documentFilter === "Todos" || (documentFilter === "Pendentes" ? pendingDocument(r) : documentFilter === "Conferir" ? toReview.includes(r) : readyDocument(r)));
  const institution = (id: string) => placements.find((p) => p.id === id)?.data.institution || "Cliente / geral";
  const draftRequest = () => { if (op) setDraft({ title: "Solicitação de documentos", text: requestDraft(op, awaitingClient) }); };
  return <section className="module-page workflow-page">
    <div className="module-heading"><div><div className="eyebrow">DO DOCUMENTO AO RESULTADO</div><h1>Acompanhamento do cliente</h1><p>Organize a documentação, prepare o envio e acompanhe cada retorno.</p></div></div>
    <div className="workflow-selector"><input aria-label="Localizar cliente no acompanhamento" placeholder="Localizar cliente…" value={search} onChange={(e) => setSearch(e.target.value)} /><select aria-label="Cliente em acompanhamento" value={selectedId} disabled={!!editing || template} onChange={(e) => select(e.target.value)}><option value="">Selecione o cliente</option>{state.operations.filter((o) => o.id === selectedId || normalizeSearch(`${o.company} ${o.cnpj}`).includes(normalizeSearch(search))).sort((a,b) => a.company.localeCompare(b.company,"pt-BR")).map((o) => <option key={o.id} value={o.id}>{o.company}</option>)}</select></div>
    {!op ? empty("Escolha um cliente para preparar o checklist, anexar documentos e organizar os retornos.") : <>
      <div className="workflow-client"><div><strong>{op.company}</strong><span>{op.stage} · Responsável: {op.owner}</span></div><span>{placements.length} instituições vinculadas</span></div>
      <div className="workflow-steps">
        {[{ title: "Solicitar ao cliente", count: awaitingClient.length, step: "01", run: () => { setTab("documents"); setDocumentFilter("Pendentes"); } },{ title: "Conferir documentos", count: toReview.length, step: "02", run: () => { setTab("documents"); setDocumentFilter("Conferir"); } },{ title: "Prontos para selecionar", count: ready.length, step: "03", run: () => setTab("dispatches") },{ title: "Acompanhar retornos", count: dispatches.filter(openDispatch).length + tasks.filter(openTask).length, step: "04", run: () => setTab("tasks") }].map((s) => <button key={s.step} onClick={s.run}><small>{s.step}</small><strong>{s.count}</strong><span>{s.title}<ArrowRight size={14} /></span></button>)}
      </div>
      <nav className="workflow-tabs" aria-label="Acompanhamento do cliente">{[["documents", "Documentos"], ["tasks", "Tarefas e retornos"], ["dispatches", "Envios às instituições"], ["client", "Atualização ao cliente"]].map(([key,label]) => <button key={key} aria-pressed={tab === key} onClick={() => setTab(key as WorkflowTab)}>{label}</button>)}</nav>
      {tab === "documents" && <>
        <div className="workflow-toolbar"><div><h2>Checklist e arquivos</h2><p>Receber o arquivo é o início. Conferir exige registrar o resultado.</p></div><div className="module-actions"><button disabled={!canEdit} onClick={() => setTemplate(true)}><ClipboardCheck size={15} /> Preparar checklist</button><button disabled={!canEdit} onClick={() => setEditing({kind:"document",record:null})}><Plus size={15} /> Exigência avulsa</button><button disabled={!awaitingClient.length} onClick={draftRequest}><Copy size={15} /> Preparar solicitação</button></div></div>
        <div className="workflow-filters"><select aria-label="Situação dos documentos" value={documentFilter} onChange={(e) => setDocumentFilter(e.target.value)}>{["Todos","Pendentes","Conferir","Conferidos"].map((s) => <option key={s}>{s}</option>)}</select><label><input type="checkbox" checked={archived} onChange={(e) => setArchived(e.target.checked)} /> Ver arquivados</label><span>{ready.length} conferidos · {pending.length} pendências obrigatórias</span></div>
        <div className="workflow-documents">{shownDocs.map((r) => <article className="workflow-document" key={r.id}>
          <div className="workflow-document-title"><FileText size={21} /><div><h3>{r.data.title}</h3><p>{r.data.entity} · {r.data.category}{r.data.period ? ` · ${r.data.period}` : ""}</p><small>{institution(r.data.placementId)} · {r.data.required ? "Obrigatório" : "Complementar"}</small></div><span className={`workflow-badge ${readyDocument(r) ? "good" : expiredDocument(r) || r.data.status === "A corrigir" ? "warning" : ""}`}>{expiredDocument(r) ? "Validade vencida" : r.data.status}</span></div>
          <div className="workflow-document-bottom"><span>Responsável: {r.data.owner}</span><span className={dateClass(r.data.dueDate)}>Prazo: {displayDate(r.data.dueDate)}</span><span>{r.data.files.length} arquivo(s){r.data.sourceUrl ? " · link externo" : ""}</span><div className="module-actions"><button onClick={() => setEditing({kind:"files",record:r})}><FolderOpen size={14} /> Arquivos</button><button aria-label={`Conferir ${r.data.title}`} onClick={() => setEditing({kind:"document",record:r})}>Abrir / conferir</button></div></div>
          {r.data.status === "A corrigir" && <p className="workflow-correction">{r.data.reviewNotes}</p>}
        </article>)}</div>
        {!shownDocs.length && empty(archived ? "Nenhum documento arquivado nesta seleção." : "Nenhum item nesta seleção. Prepare um checklist ou adicione uma exigência.")}
      </>}
      {tab === "tasks" && <>
        <button className="workflow-return" onClick={() => onEditClient(op)}><span><strong>Próximo passo do cadastro</strong><small>{op.nextAction || "Definir ação do cliente"} · {op.owner}</small></span><b className={dateClass(op.dueDate)}>{displayDate(op.dueDate)}</b><ArrowRight size={16} /></button>
        <div className="workflow-toolbar"><div><h2>Próximas ações</h2><p>Defina quem conduz e de quem depende a resposta.</p></div><button className="primary" disabled={!canEdit} onClick={() => setEditing({kind:"task",record:null})}><Plus size={15} /> Nova tarefa</button></div>
        <div className="workflow-task-list">{tasks.sort((a,b) => Number(openTask(b))-Number(openTask(a)) || (a.data.dueDate || "9999").localeCompare(b.data.dueDate || "9999")).map((r) => <button key={r.id} className="workflow-task" onClick={() => setEditing({kind:"task",record:r})}><span className="workflow-badge">{r.data.status}</span><strong>{r.data.title}</strong><span>{r.data.owner} · Depende de {r.data.waitingOn}</span><span className={openTask(r) ? dateClass(r.data.dueDate) : ""}>{displayDate(r.data.dueDate)}</span></button>)}</div>
        {!tasks.length && empty("Crie a primeira ação: pedir documentos, revisar o dossiê, cobrar a instituição ou atualizar o cliente.")}
        <h3 className="workflow-section-title">Retornos dos envios</h3>{dispatches.filter(openDispatch).map((r) => <button className="workflow-return" key={r.id} onClick={() => setEditing({kind:"dispatch",record:r})}><span><strong>{institution(r.data.placementId)}</strong><small>{r.data.nextAction} · {r.data.owner}</small></span><b className={dateClass(r.data.followUpOn)}>{displayDate(r.data.followUpOn)}</b><ArrowRight size={16} /></button>)}
        {!dispatches.some(openDispatch) && <p className="workflow-muted">Nenhum envio aguardando retorno.</p>}
      </>}
      {tab === "dispatches" && <>
        <div className="workflow-toolbar"><div><h2>Da preparação ao retorno do gerente</h2><p>Selecione documentos conferidos e registre o encaminhamento realizado pela equipe.</p></div><button className="primary" disabled={!canEdit || !placements.length || !ready.length} onClick={() => setEditing({kind:"dispatch",record:null})}><Send size={15} /> Preparar / registrar envio</button></div>
        <div className="workflow-institutions">{placements.map((r) => <button key={r.id} onClick={() => setEditing({kind:"placement",record:r})}><strong>{r.data.institution}</strong><span>{r.data.manager || "Gerente a vincular"}</span><small>{r.data.status} · {displayDate(r.data.dueDate)}</small></button>)}</div>
        {!placements.length && empty("Vincule uma instituição na carteira de operações para preparar o envio ao gerente.")}
        <div className="workflow-task-list">{dispatches.map((r) => <article key={r.id} className="workflow-dispatch"><div><span className="workflow-badge">{r.data.status}</span><h3>{institution(r.data.placementId)}</h3><p>{r.data.recipient} · {r.data.channel} · {displayDate(r.data.sentOn)}</p><small>{r.data.items.length} documentos registrados com sua versão</small></div><div><strong className={openDispatch(r) ? dateClass(r.data.followUpOn) : ""}>Retorno: {displayDate(r.data.followUpOn)}</strong><p>{r.data.nextAction}</p><button aria-label={`Acompanhar envio ${institution(r.data.placementId)} de ${r.data.sentOn}`} onClick={() => setEditing({kind:"dispatch",record:r})}>Ver envio / registrar retorno</button></div></article>)}</div>
        {!dispatches.length && <p className="workflow-muted">Os envios registrados aparecerão aqui. Preparar ou copiar uma mensagem não registra um envio realizado.</p>}
      </>}
      {tab === "client" && <div className="workflow-client-update"><div><div className="eyebrow">COMUNICAÇÃO COM O CLIENTE</div><h2>Um retorno claro, mesmo durante a análise</h2><p>Prepare uma atualização com a etapa registrada, a documentação e os próximos passos. Revise o texto antes de compartilhar.</p><button className="primary" onClick={() => setDraft({title:"Atualização ao cliente",text:clientUpdateDraft(op,records)})}><Copy size={16} /> Preparar atualização</button></div><div><strong>Antes de encaminhar</strong><ul><li>Confirme o que foi concluído desde o último contato.</li><li>Informe a pendência que depende do cliente.</li><li>Combine o próximo retorno, mesmo sem decisão do banco.</li><li>Preserve condições e aprovações ainda não confirmadas.</li></ul></div></div>}
      {editing?.kind === "files" && editing.record && <FileDrawer record={(state.records ?? []).find((r) => r.id === editing.record?.id) ?? editing.record} repo={repo} canEdit={canEdit} notify={notify} close={() => setEditing(null)} />}
      {editing?.kind === "placement" && <RecordEditor op={op} record={editing.record} kind="placement" state={state} repo={repo} canEdit={canEdit} close={() => setEditing(null)} notify={notify} />}
      {editing && ["document","task","dispatch"].includes(editing.kind) && <WorkflowEditor key={editing.record?.id ?? editing.kind} op={op} kind={editing.kind as "document" | "task" | "dispatch"} record={editing.record} state={state} repo={repo} canEdit={canEdit} close={() => setEditing(null)} notify={notify} openDraft={(text) => setDraft({title:"Mensagem ao gerente",text})} />}
      {template && <ChecklistDrawer op={op} records={records} repo={repo} close={() => setTemplate(false)} notify={notify} />}
    </>}
    {error && <p role="alert" className="module-error">{error}</p>}
    {draft && <Drawer title={draft.title} close={() => setDraft(null)}><div className="module-form"><p>Rascunho para revisão. A mensagem não será enviada automaticamente.</p><label>Mensagem<textarea rows={17} value={draft.text} onChange={(e) => setDraft({...draft,text:e.target.value})} /></label><button className="primary" onClick={async () => { try { await navigator.clipboard.writeText(draft.text); notify("Mensagem copiada. Revise o destinatário antes de enviar pelo canal escolhido."); } catch { setError("Não foi possível copiar. Selecione o texto da mensagem."); } }}><Copy size={15} /> Copiar mensagem revisada</button></div></Drawer>}
  </section>;
}

function ChecklistDrawer({ op, records, repo, close, notify }: { op: Operation; records: WorkspaceRecord[]; repo: Repository; close: () => void; notify: (text:string) => void }) {
  const [product,setProduct]=useState(op.product), [owner,setOwner]=useState(op.owner), [dueDate,setDueDate]=useState(""), [excluded,setExcluded]=useState<string[]>([]), [busy,setBusy]=useState(false), [error,setError]=useState("");
  const suggestions = documentChecklist(product);
  const existing = new Set(records.filter((r) => r.kind === "document").map((r) => r.data.templateKey));
  const selected = suggestions.filter((r) => !existing.has(r.key) && !excluded.includes(r.key));
  return <Drawer title="Preparar checklist" close={() => { if(!busy)close(); }}><form className="module-form" onSubmit={async (e) => { e.preventDefault(); setBusy(true); setError(""); let count=0; try { for(const item of selected) { await repo.saveRecord(recordInput("document",op.id,{...newDocument(op),title:item.title,category:item.category,period:item.period,requirement:item.requirement,templateKey:item.key,owner,dueDate},await checklistId(op.id,item.key)),null); count++; } notify(`${count} exigências incluídas. Ajuste períodos e exigências com a instituição.`); close(); } catch(e) { setError(`${count} itens incluídos. ${errorText(e)} Os itens já gravados foram preservados; reabra o checklist para continuar.`); } finally { setBusy(false); } }}><p>Sugestão inicial LR Capital. Selecione somente o que se aplica e ajuste a exigência com a instituição.</p><fieldset disabled={busy}><label>Modalidade do checklist<select value={product} onChange={(e) => {setProduct(e.target.value as typeof product);setExcluded([]);}}>{products.map((p)=><option key={p}>{p}</option>)}</select></label><div className="module-grid"><label>Responsável<input required maxLength={200} value={owner} onChange={(e)=>setOwner(e.target.value)} /></label><label>Prazo combinado<input type="date" value={dueDate} onChange={(e)=>setDueDate(e.target.value)} /></label></div><div className="checklist-suggestions">{suggestions.map((s)=><label key={s.key}><input type="checkbox" disabled={existing.has(s.key)} checked={existing.has(s.key)||!excluded.includes(s.key)} onChange={(e)=>setExcluded(e.target.checked?excluded.filter(k=>k!==s.key):[...excluded,s.key])}/><span><strong>{s.title}{existing.has(s.key)?" · já cadastrado":""}</strong><small>{s.period} · {s.requirement}</small></span></label>)}</div></fieldset>{error&&<p role="alert" className="module-error">{error}</p>}<button className="primary" disabled={busy||!selected.length}>{busy?"Incluindo…":`Incluir ${selected.length} exigências`}</button></form></Drawer>;
}

function FileDrawer({record,repo,canEdit,notify,close}:{record:WorkspaceRecord;repo:Repository;canEdit:boolean;notify:(s:string)=>void;close:()=>void}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState("");
  return <Drawer title={`Arquivos · ${record.data.title}`} close={()=>{if(!busy)close();}}><div className="module-form"><p>Novas versões preservam os arquivos anteriores e voltam para “Recebido”, aguardando conferência. Use um item por documento; cadastre arquivos complementares como exigências separadas.</p>{repo.uploadDocument ? <label className="workflow-upload"><Upload size={21}/><strong>{busy?"Anexando…":"Anexar arquivo / nova versão"}</strong><small>PDF, PNG, JPG, DOCX ou XLSX · até 10 MB por arquivo</small><input aria-label="Anexar documento" type="file" accept=".pdf,.png,.jpg,.jpeg,.docx,.xlsx" disabled={busy||!canEdit||record.data.archived} onChange={async(e)=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;setBusy(true);setError("");try{await repo.uploadDocument!(record.id,record.version,file);notify("Arquivo anexado. Confira o conteúdo antes de marcar como conferido.");}catch(e){setError(errorText(e));}finally{setBusy(false);}}}/></label>:<p className="module-warning">Neste ambiente, cadastre um link do Drive ou do repositório documental no item. O armazenamento de anexos em nuvem ainda precisa ser conectado.</p>}
    <div className="workflow-files">{[...record.data.files].reverse().map((file:DocumentFile,i:number)=><article key={file.id}><strong>{file.name}</strong><small>Versão {record.data.files.length-i} · {(file.size/1024).toLocaleString("pt-BR",{maximumFractionDigits:1})} KB · {new Date(file.uploadedAt).toLocaleString("pt-BR")}</small><details><summary>Identificação do arquivo</summary><code>{file.sha256}</code></details><button disabled={!repo.downloadDocument} onClick={async()=>{try{await repo.downloadDocument!(file);}catch(e){setError(errorText(e));}}}>Baixar original</button></article>)}</div>
    {record.data.sourceUrl&&<a className="workflow-link" href={record.data.sourceUrl} target="_blank" rel="noreferrer">Abrir documento no repositório externo ↗</a>}{!record.data.files.length&&!record.data.sourceUrl&&empty("Nenhum arquivo ou link associado a este item.")}{error&&<p role="alert" className="module-error">{error}</p>}<p className="module-footnote">Anexos locais ficam guardados neste computador. A exportação JSON da carteira contém o cadastro, mas não os arquivos; preserve também o backup do banco local.</p></div></Drawer>;
}

function WorkflowEditor({op,kind,record,state,repo,canEdit,close,notify,openDraft}:{op:Operation;kind:"document"|"task"|"dispatch";record:WorkspaceRecord|null;state:WorkspaceState;repo:Repository;canEdit:boolean;close:()=>void;notify:(s:string)=>void;openDraft:(s:string)=>void}) {
  const records=(state.records??[]).filter(r=>r.operationId===op.id), placements=records.filter(r=>r.kind==="placement");
  const [data,setData]=useState<Record<string,any>>(()=>record?.data??(kind==="document"?newDocument(op):kind==="task"?newTask(op):{placementId:"",recipient:"",channel:"E-mail",sentOn:today(),followUpOn:"",status:"Aguardando retorno",owner:op.owner,nextAction:"Confirmar recebimento e solicitar posição da análise",notes:"",items:[]}));
  const [selected,setSelected]=useState<string[]>([]),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const candidates=records.filter(r=>readyDocument(r)&&(!r.data.placementId||r.data.placementId===data.placementId));
  const items=record?.data.items??candidates.filter(r=>selected.includes(r.id)).map(r=>({documentId:r.id,version:r.version,title:r.data.title,fileId:r.data.files.at(-1)?.id??"",sourceUrl:r.data.sourceUrl}));
  const f=(k:string)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setData({...data,[k]:e.target.value});
  const field=(key:string,label:string,type="text",required=false)=><label>{label}<input type={type} required={required} maxLength={type==="text"?200:undefined} value={data[key]} onChange={f(key)}/></label>;
  const selectField=(key:string,label:string,values:readonly string[])=><label>{label}<select value={data[key]} onChange={f(key)}>{values.map(s=><option key={s}>{s}</option>)}</select></label>;
  const placementField=<label>Instituição vinculada<select value={data.placementId} required={kind==="dispatch"} disabled={kind==="dispatch"&&!!record} onChange={e=>{const p=placements.find(r=>r.id===e.target.value);const m=state.directory?.records.find(r=>r.id===p?.data.managerId);setData({...data,placementId:e.target.value,...(kind==="dispatch"?{recipient:m?.name||p?.data.manager||""}:{})});setSelected([]);}}><option value="">{kind==="dispatch"?"Selecione uma instituição":"Geral do cliente"}</option>{placements.map(p=><option key={p.id} value={p.id}>{p.data.institution}{p.data.manager?` · ${p.data.manager}`:""}</option>)}</select></label>;
  return <Drawer title={kind==="document"?"Exigência e conferência":kind==="task"?"Tarefa e próximo passo":record?"Acompanhar envio":"Preparar / registrar envio"} close={()=>{if(!busy)close();}}><form className="module-form" onSubmit={async(e)=>{e.preventDefault();setBusy(true);setError("");try{if(kind==="dispatch"&&!record&&!confirmed)throw new Error("Confirme o envio que você realizou antes de registrá-lo.");await repo.saveRecord(recordInput(kind,op.id,kind==="dispatch"?{...data,items}:data,record?.id??crypto.randomUUID()),record?.version??null);notify(kind==="dispatch"?"Envio e prazo de retorno registrados.":"Acompanhamento salvo.");close();}catch(e){setError(errorText(e));}finally{setBusy(false);}}}><p>{op.company}</p><fieldset disabled={!canEdit||busy}>
    {kind==="document"&&<>{field("title","Documento / exigência","text",true)}<div className="module-grid">{selectField("category","Categoria",categories)}{field("entity","Empresa / pessoa a que se refere","text",true)}</div>{field("period","Período ou competência")}{placementField}<label>Origem e motivo da exigência<textarea value={data.requirement} onChange={f("requirement")} maxLength={2000}/></label><div className="module-grid">{selectField("status","Situação documental",documentStatuses)}{field("owner","Responsável pela conferência","text",true)}</div><div className="module-grid">{field("dueDate","Prazo combinado","date")}{field("expiresOn","Validade informada no documento","date")}</div>{field("requestedOn","Solicitado ao cliente em","date")}<label>Link do documento (Drive ou repositório)<input type="url" value={data.sourceUrl} onChange={e=>setData({...data,sourceUrl:e.target.value,status:data.status==="Conferido"?"Recebido":data.status})} placeholder="https://…" maxLength={2000}/></label>{selectField("signatureCheck","Conferência de assinatura",signatureChecks)}<label>Resultado da conferência / pendência objetiva<textarea rows={4} value={data.reviewNotes} onChange={f("reviewNotes")} maxLength={2000} placeholder="Informe entidade, período, integridade, assinatura observada e correções necessárias."/></label><label className="check-field"><input type="checkbox" checked={data.required} onChange={e=>setData({...data,required:e.target.checked})}/> Obrigatório para esta operação</label><label className="check-field"><input type="checkbox" checked={data.archived} onChange={e=>setData({...data,archived:e.target.checked})}/> Arquivado (preserva cadastro e arquivos)</label><p className="module-footnote">Conferido é uma revisão da equipe. Não equivale a validação digital de assinatura nem aprovação bancária. Para anexar, salve este item e abra “Arquivos”.</p></>}
    {kind==="task"&&<>{field("title","Próxima ação","text",true)}<div className="module-grid">{field("owner","Responsável LR","text",true)}{selectField("waitingOn","Depende de quem",waitingParties)}</div>{placementField}<div className="module-grid">{field("dueDate","Prazo do retorno","date")}{selectField("status","Situação da tarefa",["Aberta","Concluída","Cancelada"])}</div>{data.status==="Concluída"&&field("completedOn","Concluída em","date",true)}<label>Resultado / contexto<textarea rows={5} value={data.notes} onChange={f("notes")} maxLength={2000}/></label></>}
    {kind==="dispatch"&&<>{placementField}{!record?<><div className="module-grid">{field("recipient","Gerente / destinatário","text",true)}{selectField("channel","Canal utilizado",["E-mail","WhatsApp","Portal da instituição","Outro"])}</div><div className="module-grid">{field("sentOn","Envio realizado em","date",true)}{field("followUpOn","Retornar até","date",true)}</div><div className="checklist-suggestions"><h3>Selecione os documentos deste envio</h3>{candidates.map(r=><label key={r.id}><input type="checkbox" checked={selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(id=>id!==r.id))}/><span><strong>{r.data.title}</strong><small>{r.data.period} · cadastro v{r.version}</small></span></label>)}{!candidates.length&&<p>Nenhum documento conferido e válido para esta instituição.</p>}</div><p className="module-footnote">Selecione apenas o que será encaminhado. Outros itens do checklist podem continuar pendentes.</p><button type="button" disabled={!items.length||!data.placementId} onClick={()=>openDraft(`Olá, ${data.recipient||"equipe"}.\n\nEncaminhamento de ${op.company} para análise de crédito.\n\nDocumentação selecionada:\n${items.map((i:any)=>`• ${i.title}`).join("\n")}\n\n${op.requestedCents===null?"Valor pretendido a confirmar.":`Valor pretendido: ${(op.requestedCents/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}.`}\nSolicitamos a confirmação de recebimento, eventuais pendências e a previsão de retorno.\n\nLR Capital`)}><Copy size={14}/> Preparar mensagem ao gerente</button><label className="check-field"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Confirmo que realizei este envio fora do sistema</label></>:<><div className="workflow-sent-details"><strong>{data.recipient} · {data.channel} · {displayDate(data.sentOn)}</strong><ul>{items.map((i:any)=>{const file=records.find(r=>r.id===i.documentId)?.data.files?.find((f:DocumentFile)=>f.id===i.fileId);return <li key={i.documentId}>{i.title} · cadastro v{i.version}{file&&repo.downloadDocument&&<button type="button" onClick={async()=>{try{await repo.downloadDocument!(file);}catch(e){setError(errorText(e));}}}>Baixar arquivo deste envio</button>}{i.sourceUrl&&<a href={i.sourceUrl} target="_blank" rel="noreferrer"> · abrir link registrado ↗</a>}</li>;})}</ul><small>Destinatário, data e versões do envio são preservados.</small></div>{field("followUpOn","Retornar até","date",true)}</>}<div className="module-grid">{field("owner","Responsável pelo retorno","text",true)}{selectField("status","Situação do envio",["Aguardando retorno","Em análise","Pendência","Concluído","Cancelado"])}</div>{field("nextAction","Próximo passo","text",true)}<label>Retorno recebido / resultado<textarea rows={4} value={data.notes} onChange={f("notes")} maxLength={2000}/></label></>}
    </fieldset>{error&&<p role="alert" className="module-error">{error}</p>}<div className="module-actions"><button type="button" onClick={close} disabled={busy}>Fechar</button><button className="primary" disabled={busy||!canEdit}>{busy?"Salvando…":kind==="dispatch"&&!record?"Registrar envio realizado":"Salvar acompanhamento"}</button></div>{record&&<details><summary>Histórico do acompanhamento</summary><p className="module-footnote">Versões disponíveis no histórico recente da equipe.</p>{(state.recordEvents??[]).filter(e=>e.recordId===record.id).sort((a,b)=>b.version-a.version).map(e=><WorkflowHistory key={e.id} event={e}/>)}</details>}</form></Drawer>;
}

function WorkflowHistory({event}:{event:RecordEvent}) {
  let data:Record<string,any>={};
  try { if(event.contentJson) data=JSON.parse(event.contentJson); } catch { /* Eventos antigos podem não ter conteúdo. */ }
  return <article className="workflow-history"><small>{new Date(event.at).toLocaleString("pt-BR")} · {event.actor} · v{event.version}</small>{data.status&&<strong>{data.status}</strong>}{(data.followUpOn||data.dueDate)&&<span>Prazo: {displayDate(data.followUpOn||data.dueDate)}</span>}{data.nextAction&&<p>{data.nextAction}</p>}{(data.reviewNotes||data.notes)&&<p>{data.reviewNotes||data.notes}</p>}</article>;
}

export function FollowUpPage({state,onOpen}:{state:WorkspaceState;onOpen:(id:string,tab:WorkflowTab)=>void}) {
  const [date,setDate]=useState(today),[filter,setFilter]=useState("Todos"),[owner,setOwner]=useState("Todos"),[party,setParty]=useState("Todos"),[search,setSearch]=useState(""),[page,setPage]=useState(1);
  useEffect(()=>{const timer=setInterval(()=>setDate(today()),60000);return()=>clearInterval(timer);},[]);
  const rows=useMemo(()=>followUps(state,date),[state,date]);
  const matches=(due:string,which:string)=>which==="Todos"||which==="Vencidos"&&!!due&&due<date||which==="Hoje"&&due===date||which==="Próximos"&&due>date||which==="Sem prazo"&&!due;
  const shown=rows.filter(r=>matches(r.dueDate,filter)&&(owner==="Todos"||owner===r.owner)&&(party==="Todos"||party===r.party)&&normalizeSearch(`${r.company} ${r.title}`).includes(normalizeSearch(search)));
  useEffect(()=>setPage(1),[filter,owner,party,search]);
  const pages=Math.max(1,Math.ceil(shown.length/50)),current=Math.min(page,pages);
  return <section className="module-page workflow-page"><div className="module-heading"><div><div className="eyebrow">ROTINA DA EQUIPE</div><h1>Próximas ações</h1><p>Compromissos do cliente, documentos, instituições e envios em uma agenda.</p></div></div><div className="workflow-agenda-metrics">{["Todos","Vencidos","Hoje","Próximos","Sem prazo"].map(s=><button key={s} aria-pressed={filter===s} onClick={()=>setFilter(s)}><span>{s}</span><strong>{rows.filter(r=>matches(r.dueDate,s)).length}</strong></button>)}</div><div className="workflow-selector"><input aria-label="Buscar na agenda" placeholder="Cliente ou próximo passo…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Responsável na agenda" value={owner} onChange={e=>setOwner(e.target.value)}><option value="Todos">Todos os responsáveis</option>{[...new Set(rows.map(r=>r.owner))].sort().map(s=><option key={s}>{s}</option>)}</select><select aria-label="Depende de quem na agenda" value={party} onChange={e=>setParty(e.target.value)}><option value="Todos">Todas as dependências</option>{waitingParties.map(s=><option key={s}>{s}</option>)}</select></div><div className="workflow-task-list">{shown.slice((current-1)*50,current*50).map(r=><button className="workflow-agenda-row" key={r.id} onClick={()=>onOpen(r.operationId,r.type==="Documento"?"documents":r.type==="Envio"||r.type==="Instituição"?"dispatches":"tasks")}><span className={`workflow-badge ${r.dueDate&&r.dueDate<date?"warning":""}`}>{r.type}</span><span><strong>{r.company}</strong><small>{r.title}</small></span><span>{r.owner}<small>Depende de {r.party}</small></span><b className={dateClass(r.dueDate)}>{displayDate(r.dueDate)}</b><ArrowRight size={15}/></button>)}</div>{!shown.length&&empty("Nenhum compromisso nesta seleção.")}<div className="portfolio-pagination"><span>{shown.length} compromissos</span><div><button disabled={current===1} onClick={()=>setPage(current-1)}>Anterior</button><span>{current} de {pages}</span><button disabled={current===pages} onClick={()=>setPage(current+1)}>Próxima</button></div></div></section>;
}
